services:
  # Servicio 1: El Motor de Base de Datos
  postgres-vector:
    image: pgvector/pgvector:pg16
    container_name: postgres_vector_db
    environment:
      POSTGRES_DB: ecommerce_vectorial
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ecommerce_vectorial"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Servicio 2: Tu Pipeline de Carga (Python automatizado)
  extractor-etl:
    build: .
    container_name: python_etl_container
    network_mode: "service:postgres-vector" # Comparte la red para conectarse por 'localhost'
    depends_on:
      postgres-vector:
        condition: service_healthy # Espera estrictamente a que Postgres acepte conexiones

volumes:
  postgres_data: